---
# The authentication token for the application.
authentication: SJGDElOyNN4OESRDxcL3qTgjIgJVyHnYCW6-XUddxgk
ignored_endpoints:
  - SessionsController#impersonate
  - SessionsController#stop_impersonating
  - LetterOpenerWeb::Engine
  - ScrapyardLeaderboardsController#index
  - Api::Hackatime::V1::HackatimeController#push_heartbeats
  - Api::Hackatime::V1::HackatimeController#status_bar_today
  - Api::V1::StatsController#user_stats
  - Rails::HealthController#show
  - AhoyCaptain::StatsController#show
  - ActionDispatch::Routing::RouteSet#*
  - ActionDispatch::Static
